[".emacs.d"]
  type = "archive"
  url = "https://codeload.github.com/syl20bnr/spacemacs/zip/refs/heads/develop"
  exact = true
  stripComponents = 1
[".config/tmux/plugins/tpm"]
  type = "archive"
  url = "https://codeload.github.com/tmux-plugins/tpm/zip/refs/heads/master"
  exact = true
  stripComponents = 1
[".fonts"]
  type = "archive"
  url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Meslo.zip"
