theme="dark_plus"

[editor.cursor-shape]
insert = "bar"

[editor]
bufferline = "multiple"
cursorline = true
true-color = true

[keys.normal]
A-z = [ ":toggle-option soft-wrap.enable", ":redraw" ]
A-r = [ ":reload-all", ":config-reload", ":redraw" ]

[keys.normal.'space'.'space']
w = [":write", ":reload", ":redraw"]
g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw", ":reload-all"]
