theme="tokyonight"

[editor.cursor-shape]
insert = "bar"

[editor]
bufferline = "multiple"
cursorline = true
true-color = true

[keys.normal]
C-h = [ "jump_view_left" ]
C-j = [ "jump_view_down" ]
C-k = [ "jump_view_up" ]
C-l = [ "jump_view_right" ]
H = [ ":buffer-previous" ]
L = [ ":buffer-next" ]
A-z = [ ":toggle-option soft-wrap.enable", ":redraw" ]
C-r = [ ":reload-all", ":config-reload", ":redraw" ]
C-space = [ "expand_selection" ]
backspace = [ "shrink_selection" ]

[keys.normal.'space'.'space']
w = [":write", ":redraw"]
g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw", ":reload-all"]
# s = ":run-shell-command zellij run -fc -- lazygit"
