theme="dark_plus"

[editor.cursor-shape]
insert = "bar"

[editor]
bufferline = "multiple"
cursorline = true

[keys.insert]
j = { j = "normal_mode" }

[keys.normal]
#like c-d in vscode
"C-n" = [
  "move_prev_word_start",
  "move_next_word_end",
  "search_selection",
  "extend_search_next",
]
A-z = [ ":toggle-option soft-wrap.enable", ":redraw" ]

[keys.normal.'space'.'space']
g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw", ":reload-all"]
